### ISSUE TITLE
O que será da Home?

### ISSUE THREAD

**Issue by JimChie** [academiadev-jlle/frontend-batatacombacon#30]

**Comment by marcoayamada** [comment]
@JimChie estava fazendo essa atividade e percebi que não temos uma definição do que será a Home page.

A Home será a listagem de pets para adoção ou cadastro de pets? O site terá abordagem mais de escolha para adoção ou cadastro de pets?

**Comment by JimChie** [comment]
Então @marcoayamada, pensei na home apenas como uma página de acesso com foco em mostrar o motivo do site. O app principal, que é mostrar os pets, ficou no discover.

**Comment by marcoayamada** [comment]
Motivo seria uma descrição curta?

**Comment by JimChie** [comment]
Tava pensando em colocarmos uma descrição curta em um dos carousel

**Comment by marcoayamada** [comment]
Você quer usar um carrossel mesmo neh 🤣🤣

**Comment by JimChie** [comment]
Hahahaha, tava só dizendo o que pensei na hora. Eu acredito que devemos colocar algo a mais. Não podemos deixar apenas aquele mapa.

**Comment by marcoayamada** [comment]
Uhmm acho que estamos pensando em coisas diferentes.
A tela que tem o mapa seria pra *incluir* um pet. Quando fiz pensei no seguinte:

- site
  - home.html (cards com vários pets)
  - incluir.html (cadastro de um novo pet. Aqui vai o mapa pra facilitar a vida do usuário)

De acordo com o que você falou, entendi:

- site
  - home.html (com carrossel :D)
  - discover.html
  - incluir.html

To certo de acordo com seu pensamento? Entendeu o que eu quis dizer com aquele mapa?

**Comment by JimChie** [comment]
Agora entendi!!
Pensei que o mapa era pra ver onde estão os pets perdidos. Viajei aqui. Então nosso home está errado...

**Comment by marcoayamada** [comment]
Essa era a discussão que eu queria haha

Sugere qual modo?

**Comment by klimber** [comment]
Estou gostando da discussão!!!

**Comment by JimChie** [comment]
Foi decidido manter o mesmo por enquanto!
