### ISSUE TITLE
Ativação do email

### ISSUE THREAD

**Issue by klimber** [academiadev-jlle/frontend-batatacombacon#96]
# Ativação do email

Assim como a maioria dos serviços web, acredito que deveriamos confirmar o email cadastrado pelos usuários antes de deixá-los criar novos pets, comentar em cards, etc...

## O método

Acredito que possa ser feito da seguinte forma:

 1. Usuário faz o cadastro no site, é enviado para o email dele um link com um token de ativação.
 2. Antes de ativar a conta, o usuário fica impedido de fazer certas ações no site, e é contemplado por uma mensagem avisando sobre isso.
 3. Ao clicar no link de ativação, é redirecionado para uma página informando da ativação com sucesso.

## Como fazer

Poderíamos criar uma variável no User:
`private Boolean emailAtivado = false;`

E ao clicar no link de ativação trocaríamos para **True**.

Essa informação seria enviada com o RequestUserDTO e poderia sempre ser vista pelo FrontEnd, para que possa ser feita a exibição das mensagens.

> Written with [StackEdit](https://stackedit.io/).

**Comment by marcoayamada** [comment]
Quando você diz:

Essa informação seria enviada com o RequestUserDTO e poderia sempre ser vista pelo FrontEnd, para que possa ser feita a exibição das mensagens.

Você já está se referindo ao auth do user ou essa informação seria apenas para ativação do cadastro?

**Comment by marcoayamada** [comment]
Se for na ativação é uma boa, porque daí mandamos o cara validar antes de usar haha

**Comment by JimChie** [comment]
Não teria uma forma por exemplo: o usuário se cadastra e só daremos o acess token dele depois dele confirmar o email ao invés de utilizar mais uma variável? Só uma idéia na verdade porque eu não sei como o backend iria fazer isso.

**Comment by klimber** [comment]
Também ainda tenho poucas idéias de como isso tudo funciona na prática, vou tentar ler um pouco sobre como funciona toda a parte de autenticação

**Comment by JimChie** [comment]
Eu tava pensando agora e com a minha idéia teríamos que criar um boolean que ativa ou não o usuário. Acredito que seja mais trabalhoso porque tem que separar dos usuários ativados e os não. Então na minha opinião a sua abordagem é a melhor.
